# Tell cask where to install apps
cask_args appdir: "/Applications"

# Install brew things
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "ack"
brew "autoconf"
brew "automake"
brew "openssl"
brew "readline"
brew "sqlite"
brew "aws-shell"
brew "coreutils"
brew "dark-mode"
brew "git"
brew "go"
brew "htop"
brew "hub"
brew "libksba"
brew "libtool"
brew "libyaml"
brew "macvim", args: ["HEAD"]
brew "mas"
brew "mongodb"
brew "nmap"
brew "openssl@1.1"
brew "pkg-config"
brew "speedtest-cli"
brew "thefuck"
brew "tree"
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
cask "docker"
cask "robo-3t"
cask "slack"
cask "visual-studio-code"
mas "Xcode", id: 497799835
